config/routes.rb
Rails.application.routes.draw do
  
   
   
  devise_for :users 
  
  resources :users
  
  resources :comments
  
  resources :posts
  
  resources :searches
  
  resources :usersearches
  
  
  root 'posts#index'
  
  resources :conversations do
    resources :messages
  end

end
  

app/models/search.rb
class Search < ActiveRecord::Base
    
    def search_posts
        
        posts = Post.all
        posts = posts.where(["address LIKE ?", address]) if address.present?
        posts = posts.where(["price >= ?", min_price]) if min_price.present?
        posts = posts.where(["price <= ?", max_price]) if max_price.present?
    
        return posts
    end
    
  
    
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    
    def new
    @search = Search.new
    @address = Post.uniq.pluck(:address)
    end
    
    def create
    @search = Search.create(search_params)
    redirect_to @search
    end

    def show
        @search = Search.find(params[:id])
    end
    
    private
    
    def search_params
        params.require(:search).permit(:keywords, :address, :min_price, :max_price)
    end
    
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<%= form_for @search, html: {class:"pure-form"} do |s| %>

<div class="field">
    <%= s.label :keywords %><br/>
    <%= s.text_field :keywords %>
</div>

<div class="field">
    <%= s.label :address %><br/>
    <%= s.text_field :address %>
</div>

<div class="field">
    <p><%= s.label :min_price, "Min Price" %> - <%= s.text_field :min_price, size: 10 %></p>
    <p><%= s.label :min_price, "Max Price" %> - <%= s.text_field :max_price, size: 10 %></p>
</div>

<div class="actions"><%= s.submit "Search", class: "pure-button pure-button-primary"%></div>
<% end %>

<p><%= link_to 'Back' , posts_path %></p>

app/views/searches/show.html.erb
<h1>Search Results</h1>

<p><%= link_to 'Back', new_search_path %></p>

<% if @search.search_posts.empty? %>

<p>No Listings found</p>

<% else %>

<% @search.search_posts.each do |c| %>
<br>

<div class = "div">
    <h1><%= link_to c.title, post_path(c.id) %></h1>
    <p>Price: €<%= c.price %></p>
    <p>Address: <%= c.address %></p>
   
</div>

<% end %>
<% end %>