config/routes.rb
Rails.application.routes.draw do
  
   
   
  devise_for :users 
  
  resources :users
  
  resources :comments
  
  resources :posts
  
  resources :searches
  
  resources :usersearches
  
  
  root 'posts#index'
  
  resources :conversations do
    resources :messages
  end

end
  

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    
    has_attached_file :image, :style => { :medium => "300x300>"}
     validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
     
     
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Ad was successfully removed' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image, :price, :address)
    end
    
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, html: {multipart: true} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Remove your Ad', @post, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8&appId=325771567809411";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<p id="notice"><%= notice %></p>

<h1>Listings</h1>



<table class="table table-hover">

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <th scope="row"><li><%=link_to image_tag post.user.image, :size => '100x100' %></th>
        <td><strong>Listing:</strong></br><%= post.title %></td>
        <td><strong>Address:</strong></br><%= post.address %></td>
        <td><strong>Price: </strong></br><%= post.price %></td>
        <td><strong>Last Updated: </strong></br><%= post.updated_at.to_date %></td>
        <td><strong>Renter Profile: </strong></br><%= link_to post.user.user_name, user_path(post.user) %></td>
        <td><%= link_to image_tag post.image.url, :size => '150x150' %></td>
        <td><%= link_to 'View Room', post, class: "btn btn-large btn-primary" %></td>
        <td><div class="fb-like"  data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></td>
       
        <% if post.user == current_user %>
        <td><%= link_to 'Edit your Ad', edit_post_path(post) %></td>
        <td><%= link_to 'Remove your Ad', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>
      </tr>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-hover">

  <tbody>
      <tr>
        <p><strong><%= @post.title %></strong></p>
        <p><strong><%= @post.address %></strong></p>
        <p><strong><%= @post.price %></strong></p>
        <p><strong><%= @post.updated_at.to_date %></strong></p>
        <p>
  <strong>Renter:</strong>
  <%=link_to @post.user.user_name, user_path %>
</p>

        
      </tr>
  </tbody>
</table>


<div class="container">
    <div id="main_area">
        <!-- Slider -->
        <div class="row">
            <div class="col-sm-6" id="slider-thumbs">
                <!-- Bottom switcher of slider -->
                <ul class="hide-bullets">
              
            <div class="col-sm-6">
                <div class="col-xs-12" id="slider">
                    <!-- Top part of the slider -->
                    <div class="row">
                        <div class="col-sm-12" id="carousel-bounding-box">
                            <div class="carousel slide" id="myCarousel">
                                <!-- Carousel items -->
                                <div class="carousel-inner">
                                    <div class="active item" data-slide-number="0">
                                        <%= link_to image_tag @post.image %></div>

                                    <div class="item" data-slide-number="1">
                                        <%= link_to image_tag @post.image %></div>

                                    <div class="item" data-slide-number="2">
                                        <img src="http://placehold.it/470x480&text=2"></div>

                                    <div class="item" data-slide-number="3">
                                        <img src="http://placehold.it/470x480&text=3"></div>

                                    <div class="item" data-slide-number="4">
                                        <img src="http://placehold.it/470x480&text=4"></div>

                                    <div class="item" data-slide-number="5">
                                        <img src="http://placehold.it/470x480&text=5"></div>
                    
                                <!-- Carousel nav -->
                                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                                    <span class="glyphicon glyphicon-chevron-left"></span>
                                </a>
                                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                                    <span class="glyphicon glyphicon-chevron-right"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--/Slider-->
        </div>

    </div>
</div>





<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>